### ISSUE TITLE
Fix alpha calculation

### ISSUE THREAD

**Issue by tho-** [CoreELEC/splash-image#2]
In `full_alpha_transparency`, `alpha` is computed as an integer division, so it will be either 0.0 or 1.0.
Probably not what is intended :)

Using `.../255.` instead of `.../255` will fix that.

[alpha.txt](https://github.com/CoreELEC/splash-image/files/6528026/alpha.txt)

**Comment by Portisch** [comment]
This is compiler dependent and maybe true, yes. Maybe this was the reason the alpha blend didn't show clear edges where the alpha was not 100%.

Thank you, i will pick this for the splash tool.

**Comment by tho-** [comment]
On Sunday 23 May 2021, at 10:40, Portisch wrote:
> This is compiler dependent and maybe true, yes. Maybe this was the
> reason the alpha blend didn't show clear edges where the alpha was
> not 100%.

This should not be compiler dependent. The C standard mandates that
integer division is an integer. What is more undefined is the rounding
towards zero, but this is irrelevant here.
Then, the cast to the `double` lvalue happens only afterwars.

So, in C, you always have this:

double x = 127/255;
/* x == 0 */

double y = (double)127/255; /* equivalent to 127.0/255 or 127/255.0 */
/* y roughly equal to .4980... */

**Comment by Portisch** [comment]
It looks like it does not work correct when apply https://github.com/CoreELEC/splash-image/commit/19062175ccf11f7db137b99b2f8049e2bb6ed5d4:

<img src="https://user-images.githubusercontent.com/3938570/119486338-6ee1de00-bd58-11eb-8713-6d132cacd7b9.jpg" width="200">

There is now a yellow line around the animation frames.

**Comment by tho-** [comment]
I noticed that there is a bit of transparency at the edge of the animation images.
The APPLY_ALPHA macro needs probably fixing with something like this patch (not tested).
[blend.txt](https://github.com/CoreELEC/splash-image/files/6538827/blend.txt)

**Comment by Portisch** [comment]
This indeed fixes the issue, thank you.
